# Week 1 — Data Cleaning and Exploration

**Name:** Gabriela

**Project:** Applicant Dataset Analysis

## Objective

The objective of this project is to clean and explore an applicant dataset using Python and Pandas. The process includes identifying missing values, removing duplicate records, standardizing text, and correcting data types.

In [ ]:

import pandas as pd

In [ ]:

import pandas as pd

# Create a fictional applicant dataset
data = {
    "Applicant_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 102, 112],
    "Name": [
        "Ana Silva", "Bruno Costa", "Maria Santos", "Pedro Manuel",
        "Carla Mendes", "Joao Paulo", "Sofia Lima", "Daniel Alves",
        "Beatriz Gomes", "Lucas Pereira", "Bruno Costa", "Ines Rocha"
    ],
    "Age": [24, 29, None, 35, 27, 22, 31, None, 26, 28, 29, 24],
    "Gender": [
        "Female", "Male", "FEMALE", "Male", "female", "Male",
        "Female", "MALE", "Female", "Male", "Male", "Female"
    ],
    "Education": [
        "Bachelor", "Master", "Bachelor", "PhD", "Bachelor",
        "High School", "Master", "Bachelor", "Master", "Bachelor",
        "Master", "Bachelor"
    ],
    "Years_Experience": [2, 5, 3, 10, None, 1, 7, 4, 2, 6, 5, 0],
    "Applied_Position": [
        "Data Analyst", "Software Engineer", "Data Analyst",
        "Data Scientist", "Business Analyst", "Intern",
        "Data Analyst", "Software Engineer", "Business Analyst",
        "Data Scientist", "Software Engineer", "Intern"
    ],
    "Application_Status": [
        "Accepted", "Rejected", "Under Review", "Accepted",
        "Rejected", "under review", "Accepted", "Rejected",
        "Accepted", "Under Review", "Rejected", "Accepted"
    ],
    "Expected_Salary": [
        2500, 4000, 2800, 6000, None, 1200,
        3500, 4200, 3000, 5000, 4000, 1000
    ]
}

df = pd.DataFrame(data)

# Save the fictional dataset as a CSV file
df.to_csv("applicants.csv", index=False)

print("Dataset created successfully!")
print("Dataset shape:", df.shape)

df.head()

Dataset created successfully!
Dataset shape: (12, 9)

,Applicant_ID,Name,Age,Gender,Education,Years_Experience,Applied_Position,Application_Status,Expected_Salary
0,101,Ana Silva,24.0,Female,Bachelor,2.0,Data Analyst,Accepted,2500.0
1,102,Bruno Costa,29.0,Male,Master,5.0,Software Engineer,Rejected,4000.0
2,103,Maria Santos,NaN,FEMALE,Bachelor,3.0,Data Analyst,Under Review,2800.0
3,104,Pedro Manuel,35.0,Male,PhD,10.0,Data Scientist,Accepted,6000.0
4,105,Carla Mendes,27.0,female,Bachelor,NaN,Business Analyst,Rejected,NaN

In [ ]:


print("Dataset dimensions:", df.shape)


df.info()


print("\nMissing values per column:")
print(df.isnull().sum())


print("\nNumber of duplicate rows:")
print(df.duplicated().sum())

Dataset dimensions: (12, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Applicant_ID        12 non-null     int64
 1   Name                12 non-null     object
 2   Age                 10 non-null     float64
 3   Gender              12 non-null     object
 4   Education           12 non-null     object
 5   Years_Experience    11 non-null     float64
 6   Applied_Position    12 non-null     object
 7   Application_Status  12 non-null     object
 8   Expected_Salary     11 non-null     float64
dtypes: float64(3), int64(1), object(5)
memory usage: 996.0+ bytes

Missing values per column:
Applicant_ID          0
Name                  0
Age                   2
Gender                0
Education             0
Years_Experience      1
Applied_Position      0
Application_Status    0
Expected_Salary       1
dtype: int64

Number of duplicate rows:
1

In [ ]:

print(df.isnull().sum())

Applicant_ID          0
Name                  0
Age                   2
Gender                0
Education             0
Years_Experience      1
Applied_Position      0
Application_Status    0
Expected_Salary       1
dtype: int64

In [ ]:


print("Completely duplicated rows:")
print(df.duplicated().sum())


print("\nRepeated Applicant IDs:")
print(df[df["Applicant_ID"].duplicated(keep=False)].sort_values("Applicant_ID"))

Completely duplicated rows:
1

Repeated Applicant IDs:
    Applicant_ID         Name   Age Gender Education  Years_Experience  \
1            102  Bruno Costa  29.0   Male    Master               5.0
10           102  Bruno Costa  29.0   Male    Master               5.0

     Applied_Position Application_Status  Expected_Salary
1   Software Engineer           Rejected           4000.0
10  Software Engineer           Rejected           4000.0

In [ ]:


df = df.drop_duplicates()

print("Dataset shape after removing duplicates:", df.shape)

print("Remaining duplicate rows:", df.duplicated().sum())

Dataset shape after removing duplicates: (11, 9)
Remaining duplicate rows: 0

In [ ]:

print("Median age:", df["Age"].median())
print("Median years of experience:", df["Years_Experience"].median())
print("Median expected salary:", df["Expected_Salary"].median())

Median age: 27.0
Median years of experience: 3.5
Median expected salary: 3250.0

In [ ]:

df["Age"] = df["Age"].fillna(df["Age"].median())
df["Years_Experience"] = df["Years_Experience"].fillna(
    df["Years_Experience"].median()
)
df["Expected_Salary"] = df["Expected_Salary"].fillna(
    df["Expected_Salary"].median()
)


print("Missing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
Applicant_ID          0
Name                  0
Age                   0
Gender                0
Education             0
Years_Experience      0
Applied_Position      0
Application_Status    0
Expected_Salary       0
dtype: int64

In [ ]:

print("Gender categories:")
print(df["Gender"].unique())

print("\nApplication status categories:")
print(df["Application_Status"].unique())

Gender categories:
['Female' 'Male' 'FEMALE' 'female' 'MALE']

Application status categories:
['Accepted' 'Rejected' 'Under Review' 'under review']

In [ ]:

df["Gender"] = df["Gender"].str.strip().str.title()

df["Application_Status"] = (
    df["Application_Status"].str.strip().str.title()
)


print("Gender categories after cleaning:")
print(df["Gender"].unique())

print("\nApplication status categories after cleaning:")
print(df["Application_Status"].unique())

Gender categories after cleaning:
['Female' 'Male']

Application status categories after cleaning:
['Accepted' 'Rejected' 'Under Review']

In [ ]:

print(df.dtypes)

#
df["Age"] = df["Age"].astype(int)
df["Years_Experience"] = df["Years_Experience"].astype(int)


print(df.dtypes)

#

print("Dataset shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

print("\nFirst five rows:")
display(df.head())

Applicant_ID            int64
Name                   object
Age                   float64
Gender                 object
Education              object
Years_Experience      float64
Applied_Position       object
Application_Status     object
Expected_Salary       float64
dtype: object
Applicant_ID            int64
Name                   object
Age                     int64
Gender                 object
Education              object
Years_Experience        int64
Applied_Position       object
Application_Status     object
Expected_Salary       float64
dtype: object
Dataset shape: (11, 9)

Missing values:
Applicant_ID          0
Name                  0
Age                   0
Gender                0
Education             0
Years_Experience      0
Applied_Position      0
Application_Status    0
Expected_Salary       0
dtype: int64

Duplicate rows: 0

First five rows:

,Applicant_ID,Name,Age,Gender,Education,Years_Experience,Applied_Position,Application_Status,Expected_Salary
0,101,Ana Silva,24,Female,Bachelor,2,Data Analyst,Accepted,2500.0
1,102,Bruno Costa,29,Male,Master,5,Software Engineer,Rejected,4000.0
2,103,Maria Santos,27,Female,Bachelor,3,Data Analyst,Under Review,2800.0
3,104,Pedro Manuel,35,Male,PhD,10,Data Scientist,Accepted,6000.0
4,105,Carla Mendes,27,Female,Bachelor,3,Business Analyst,Rejected,3250.0

In [ ]:



print("Number of rows and columns:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

print("\nUnique applicant IDs:", df["Applicant_ID"].nunique())

print("\nDataset preview:")
display(df.head())


# Save the cleaned dataset
df.to_csv("applicants_cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")

Number of rows and columns: (11, 9)

Missing values:
Applicant_ID          0
Name                  0
Age                   0
Gender                0
Education             0
Years_Experience      0
Applied_Position      0
Application_Status    0
Expected_Salary       0
dtype: int64

Duplicate rows: 0

Unique applicant IDs: 11

Dataset preview:

,Applicant_ID,Name,Age,Gender,Education,Years_Experience,Applied_Position,Application_Status,Expected_Salary
0,101,Ana Silva,24,Female,Bachelor,2,Data Analyst,Accepted,2500.0
1,102,Bruno Costa,29,Male,Master,5,Software Engineer,Rejected,4000.0
2,103,Maria Santos,27,Female,Bachelor,3,Data Analyst,Under Review,2800.0
3,104,Pedro Manuel,35,Male,PhD,10,Data Scientist,Accepted,6000.0
4,105,Carla Mendes,27,Female,Bachelor,3,Business Analyst,Rejected,3250.0

Cleaned dataset saved successfully!

In [ ]:
from google.colab import files

files.download("applicants_cleaned.csv")

## Conclusion

In this project, I created and cleaned a fictional applicant dataset using Python and Pandas.

The main data cleaning steps included:

1. Identifying missing values in the `Age`, `Years_Experience`, and `Expected_Salary` columns.
2. Removing one completely duplicated row.
3. Standardizing text values in the `Gender` and `Application_Status` columns.
4. Converting `Age` and `Years_Experience` to integer data types.
5. Validating the dataset after cleaning.

Missing numerical values were filled using the median of each column.

The final dataset contains 11 rows and 9 columns, with no missing values or completely duplicated rows.

This exercise helped me understand the importance of data quality and how Python and Pandas can be used to prepare data for analysis.